---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: systemd-reloader
    app.kubernetes.io/version: v0.1
  name: systemd-reloader
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: systemd-reloader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: systemd-reloader
        app.kubernetes.io/version: v0.1
    spec:
      containers:
      - command:
        - /usr/bin/env
        - bash
        - -c
        - "set -euo pipefail\nif [[ \"$(id -u)\" != 0 ]]; then\n  printf 'This script\
          \ must be run as root (uid=0), not uid=%d!\\n' \"$(id -u)\" >&2\n  exit\
          \ 1\nfi\nwhile true; do\n  printf 'Reloading systemd daemon ...\\n'\n  chroot\
          \ /host systemctl daemon-reload\n  sleep \"$PAUSE_INTERVAL\"\n  printf 'Resetting\
          \ failed units ...\\n'\n  chroot /host systemctl reset-failed\n  sleep \"\
          $PAUSE_INTERVAL\"\n  printf 'Restarting crio ...\\n'\n  chroot /host systemctl\
          \ restart crio\n  printf 'Going to sleep for %s\\n' \"$SLEEP_INTERVAL\"\n\
          \  sleep \"$SLEEP_INTERVAL\"\ndone\n"
        env:
        - name: SLEEP_INTERVAL
          value: 23h
        - name: PAUSE_INTERVAL
          value: 10m
        image: registry.access.redhat.com/ubi8@sha256:060d7d6827b34949cc0fc58a50f72a5dccf00a4cc594406bdf5982f41dfe6118
        imagePullPolicy: IfNotPresent
        name: reloader
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 8m
            memory: 50Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /host
          mountPropagation: HostToContainer
          name: root
          readOnly: true
      dnsPolicy: ClusterFirst
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      serviceAccount: systemd-reloader
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
          type: ''
        name: root
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: systemd-reloader
