---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: sdimetrics
    app.kubernetes.io/version: v0.1
  name: sdimetrics-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sdimetrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sdimetrics-exporter
        app.kubernetes.io/version: v0.1
    spec:
      containers:
        - image: quay.io/miminar/sdimetrics:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2112
              name: metrics
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 2112
          readinessProbe:
            tcpSocket:
              port: 2112
          name: node-exporter
          resources:
            requests:
              cpu: 8m
              memory: 180Mi
            limits:
              memory: 500Mi
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /host/proc
              name: proc
            - mountPath: /host/sys
              name: sys
            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: root
              readOnly: true
      dnsPolicy: ClusterFirst
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      serviceAccount: sdimetrics-exporter
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /proc
            type: ""
          name: proc
        - hostPath:
            path: /sys
            type: ""
          name: sys
        - hostPath:
            path: /
            type: ""
          name: root
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdimetrics-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sdimetrics-exporter
    app.kubernetes.io/version: v0.1
  name: sdimetrics-exporter
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 2112
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: sdimetrics-exporter
  sessionAffinity: None
  type: ClusterIP
