---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: sdimetrics
    app.kubernetes.io/version: v0.1
  name: sdimetrics-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sdimetrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sdimetrics-exporter
        app.kubernetes.io/version: v0.1
    spec:
      containers:
      - image: quay.io/miminar/sdimetrics@sha256:fa002cc24bb4208d40d91dfc63efc6a6b050652895c7d5df93fe2fb8fcccf9a6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 2112
        name: node-exporter
        ports:
        - containerPort: 2112
          name: metrics
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 2112
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 8m
            memory: 180Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /host/proc
          name: proc
        - mountPath: /host/sys
          name: sys
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
      dnsPolicy: ClusterFirst
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      serviceAccount: sdimetrics-exporter
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /proc
          type: ''
        name: proc
      - hostPath:
          path: /sys
          type: ''
        name: sys
      - hostPath:
          path: /
          type: ''
        name: root
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdimetrics-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sdimetrics-exporter
    app.kubernetes.io/version: v0.1
  name: sdimetrics-exporter
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 2112
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: sdimetrics-exporter
  sessionAffinity: None
  type: ClusterIP
