---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: sdimetrics-exporter
  name: sdimetrics-exporter
spec:
  podMetricsEndpoints:
    - interval: 10s
      port: metrics
      scheme: http
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/name: sdimetrics-exporter
