---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: sdimetrics-exporter
  name: sdimetrics-exporter
spec:
  podMetricsEndpoints:
    - interval: 10s
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: sdimetrics-exporter
